<?xml version="1.0"?>
<robot name="env" xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:macro name="env" params="single_arm_setup use_fake_hardware fake_sensor_commands ur_type:='' robot_ip robot_ip_2:='' headless_mode:='true'">
  <link name="world"/>
  <link name="start"/>
  <link name="end"/>

  <!--Robot-->
  <xacro:include filename="$(find dual_arm_test)/urdf/ur_macro.xacro"/>

  <link name="multi_arm_base_link"/>

  <joint name="multi_arm_base_joint" type="fixed">
    <origin xyz="0.5 0.0 0.0" />
    <parent link="robot_table"/>
    <child link="multi_arm_base_link"/>
  </joint>

  <xacro:unless value="${single_arm_setup}">
    <link name="robot_table_1"/>
    <link name="robot_table_2"/>
    <joint name="robot_table_to_base1" type="fixed">
      <origin xyz="0 -0.6 0" rpy="0 0 0"/>
      <parent link="multi_arm_base_link"/>
      <child link="robot_table_1"/>
    </joint>
    <joint name="robot_table_to_base2" type="fixed">
      <origin xyz="0 0.6 0" rpy="0 0 0"/>
      <parent link="multi_arm_base_link"/>
      <child link="robot_table_2"/>
    </joint>
    <xacro:env_ur
      ur_type="ur10e" 
      parent_link="robot_table_1" 
      tf_prefix="robot1/" 
      use_fake_hardware="${use_fake_hardware}"
      fake_sensor_commands="${fake_sensor_commands}"
      generate_ros2_control_tag="true"
      robot_ip="${robot_ip}"
      script_command_port="50005"
      reverse_port="50001"
      script_sender_port="50002"
      trajectory_port="50004"
      non_blocking_read="true"
      keep_alive_count="10"
      headless_mode:="${headless_mode}"
      />

    <xacro:env_ur
      ur_type="ur5e" 
      parent_link="robot_table_2" 
      tf_prefix="robot2/" 
      use_fake_hardware="${use_fake_hardware}"
      fake_sensor_commands="${fake_sensor_commands}"
      generate_ros2_control_tag="true"
      robot_ip="${robot_ip_2}"
      script_command_port="60005"
      reverse_port="60001"
      script_sender_port="60002"
      trajectory_port="60004"
      non_blocking_read="true"
      keep_alive_count="10"
      headless_mode:="${headless_mode}"/>
  </xacro:unless>

  <xacro:if value="${single_arm_setup}">
    <xacro:env_ur
    ur_type="${ur_type}"
    parent_link="robot_table" 
    tf_prefix="robot1/"
    use_fake_hardware="${use_fake_hardware}"
    fake_sensor_commands="${fake_sensor_commands}"
    generate_ros2_control_tag="true"
    joint_limits_file="$(find ur_description)/config/ur5e/joint_limits.yaml"
    robot_ip="${robot_ip}"
    script_command_port="60005"
    reverse_port="60001"
    script_sender_port="60002"
    trajectory_port="60004"
    non_blocking_read="true"
    keep_alive_count="10"
    headless_mode:="${headless_mode}"/>
  </xacro:if>

  <!--Joints-->
  <xacro:if value="${single_arm_setup}">
    <joint name="world_to_start" type="fixed">
      <parent link="world"/>
      <child link="start"/>
      <origin xyz="-1.5 -1 1.3 " rpy="0 ${radians(-90)} ${radians(90)}"/>
    </joint>

    <joint name="world_to_end" type="fixed">
      <parent link="world"/>
      <child link="end"/>
      <origin xyz="-1.0 1.0 1.3" rpy="${radians(-90)} 0 0"/>
    </joint>
  </xacro:if>

  <xacro:unless value="${single_arm_setup}">
    <joint name="world_to_start" type="fixed">
      <parent link="world"/>
      <child link="start"/>
      <origin xyz="-0.125 0 1.7 " rpy="${radians(90)} 0 0"/>
    </joint>

    <joint name="world_to_end" type="fixed">
      <parent link="world"/>
      <child link="end"/>
      <origin xyz="0.2 0.1 1.0" rpy="${radians(90)} 0 0"/>
    </joint>

    <joint name="world_to_obstacle" type="fixed">
      <parent link="world"/>
      <child link="obstacle"/>
      <origin xyz="-0.05 0 1.25" rpy="0 0 0"/>
    </joint>
  </xacro:unless>

  <joint name="world_to_robot_table" type="fixed">
    <origin xyz="${-robot_table_w / 2} 0.0 ${robot_table_h}" />
    <parent link="world"/>
    <child link="robot_table"/>
  </joint>

  <joint name="ABB_object_to_world" type="fixed">
    <origin xyz="${(-robot_table_w) + (ABB_w / 2) } ${6 * in_m} ${robot_table_h + ABB_h}" rpy="0.0 0.0 0.0"/>
    <parent link="world"/>
    <child link="ABB"/>
  </joint>
</xacro:macro>
</robot>
