controller_manager:
  ros__parameters:
    update_rate: 600  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    robot1_force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

#    faked_forces_controller:
#      type: forward_command_controller/MultiInterfaceForwardCommandController

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_state_broadcaster:
  ros__parameters:
    use_local_topics: True

robot1_force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: robot1/tcp_fts_sensor
    frame_id: robot1/wrist_3_link
    additional_frames_to_publish: [robot1/base_link]

#faked_forces_controller:
#  ros__parameters:
#    joint: robot1/tcp_fts_sensor
#    interface_names:
#      - force.x
#      - force.y
#      - force.z
#      - torque.x
#      - torque.y
#      - torque.z

joint_trajectory_controller:
  ros__parameters:
    joints:
      - robot1/shoulder_pan_joint
      - robot1/shoulder_lift_joint
      - robot1/elbow_joint
      - robot1/wrist_1_joint
      - robot1/wrist_2_joint
      - robot1/wrist_3_joint
      - robot2/shoulder_pan_joint
      - robot2/shoulder_lift_joint
      - robot2/elbow_joint
      - robot2/wrist_1_joint
      - robot2/wrist_2_joint
      - robot2/wrist_3_joint
    command_joints:
      - robot1/shoulder_pan_joint
      - robot1/shoulder_lift_joint
      - robot1/elbow_joint
      - robot1/wrist_1_joint
      - robot1/wrist_2_joint
      - robot1/wrist_3_joint
      - robot2/shoulder_pan_joint
      - robot2/shoulder_lift_joint
      - robot2/elbow_joint
      - robot2/wrist_1_joint
      - robot2/wrist_2_joint
      - robot2/wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 200.0 # Defaults to 50 - is 100 in the ur_control launch file
    action_monitor_rate: 20.0 # Defaults to 20
    allow_partial_joints_goal: false # Defaults to false
#    open_loop_control: true
#    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
